#!/bin/bash

mm_cfg_file="/etc/kafka-rest/kafka-rest.properties"

: ${MM_STREAMS:=2}
: ${MM_TOPICS:=".*"}

export MM_STREAMS
export MM_TOPICS

# Download the config file, if given a URL
if [ ! -z "$RP_CFG_URL" ]; then
  echo "[RP] Downloading RP config file from ${RP_CFG_URL}"
  curl --location --silent --insecure --output ${mm_cfg_file} ${MM_CFG_URL}
  if [ $? -ne 0 ]; then
    echo "[MM] Failed to download ${MM_CFG_URL} exiting."
    exit 1
  fi
fi

echo '# Generated by rest-proxy-docker.sh' > ${rp_cfg_file}
for var in $(env | grep -v '^MM_CFG_' | grep '^MM_' | sort); do
  key=$(echo $var | sed -r 's/MM_(.*)=.*/\1/g' | tr A-Z a-z | tr _ .)
  value=$(echo $var | sed -r 's/.*=(.*)/\1/g')
  echo "${key}=${value}" >> ${rp_cfg_file}
done

exec /usr/bin/kafka-run-class kafka.tools.MirrorMaker --consumer.config sourceCluster1Consumer.config --consumer.config sourceCluster2Consumer.config --num.streams $MM_STREAMS --producer.config targetClusterProducer.config --whitelist="${MM_TOPICS}"
